module.exports = [
  {
    filename: "raw_img/attractions/LSC-1809Tastings.jpg",
    alt: "David created 1809 Tasting series for Laurel Spring Cidery in Fall 2024 to immerse the community between the log house and barn both built in 1809",

    rowSpan: 1,
    colSpan: 1,
    width: "800",
  },
  {
    filename: "raw_img/attractions/DavidAllPours.jpg",
    alt: "Pouring an American Basque style heritage craft cider at 1809 Tastings",
    rowSpan: 2,
    colSpan: 2,
    width: "500",
  },
  {
    filename: "raw_img/attractions/HealthinAmerica.png",
    alt: "David created 'Health in America' a series of storytelling events at the National Press Club in Washington, DC featuring changemakers",
    rowSpan: 1,
    colSpan: 2,
    width: "600",
  },
  {
    filename: "raw_img/attractions/carhenge_wren.jpg",
    alt: "a person with a beard and short pink hair, wearing sunglasses, looks away from the camera. they're sitting on a grey-painted car, and Carhenge appears in the background",
    rowSpan: 2,
    colSpan: 1,
    width: "300",
  },
  {
    filename: "raw_img/attractions/carhenge_loves.jpg",
    alt: "Cassey and a person with a beard and short pink hair, both wearing sunglasses and hugging, stand in the foreground with Carhenge in the background",
    rowSpan: 2,
    colSpan: 2,
    width: "600",
  },
  {
    filename: "raw_img/attractions/cars_cars.jpg",
    alt: "two real-life cars that are made to look like Mater and Lightning McQueen from the Cars movie using big emotive facial features",

    rowSpan: 1,
    colSpan: 2,
    width: "400",
  },
  {
    filename: "raw_img/attractions/classic_head.jpg",
    alt: "a statue that looks a head that got knocked off a greco-roman is planted in a grassy yard",
    rowSpan: 1,
    colSpan: 1,
    width: "300",
  },
  {
    filename: "raw_img/attractions/capitol.jpg",
    alt: "A piece of felt with BLM stitched on it is stapled to a pole in the foreground, with the Nebraska state capitol building rising in the background",
    rowSpan: 1,
    colSpan: 2,
    width: "600",
  },
  {
    filename: "raw_img/attractions/clay-sculptures.jpg",
    alt: "on the ground at the corner of a porch sits two clay sculptures, each about 2-3 feet tall. one is of a team-sized gatorade dispenser complete with painted logo, and the other is of a triangle shaped mask and covered in painted zebra stripes",
    rowSpan: 1,
    colSpan: 1,
    width: "400",
  },
  {
    filename: "raw_img/attractions/hbd_big_jeff.jpg",
    alt: "a sign with multicolored letters hangs in the window of a building. the sign reads 'Happy birthday big Jeff' in all caps",
    rowSpan: 1,
    colSpan: 1,
    width: "300",
  },
  {
    filename: "raw_img/attractions/modern_tv.jpg",
    alt: "a DirectTv satelite dish sticks out of a toilet in the yard of a house. the toilet has decaying plant matter in it, too.",
    rowSpan: 1,
    colSpan: 1,
    width: "300",
  },
  {
    filename: "raw_img/attractions/ravenna.jpg",
    alt: "Cassey stands in front of a mid-chest-height mural of the word 'Ravenna' painted over a river background",
    rowSpan: 1,
    colSpan: 2,
    width: "600",
  },
  {
    filename: "raw_img/attractions/thinking about carhenge copy.jpg",
    alt: "Cassey, who appears in the photo as a person with long red hair an sunglasses, looks towards Carhenge in the distance, a replica of stonehenge made entirely of old cars painted grey",
    rowSpan: 1,
    colSpan: 1,
    width: "600",
  },
  {
    filename: "raw_img/attractions/windmills.jpg",
    alt: "a field full of rusty windmills",
    rowSpan: 1,
    colSpan: 3,
    width: "600",
  },
  {
    filename: "raw_img/attractions/veggies.png",
    alt: "two images side by side: one of Cassey standing under a sculpture of corn in the shape of an airplane hanging from the ceiling of an airport waiting room, the other of Cassey standing proudly next to a carrot in the shape of a rocket about to blast off",
    rowSpan: 1,
    colSpan: 2,
    width: "600",
  },
];
